version: "#{build}"
clone_depth: 1

environment:
  GULP_TASK: "test-functional-local"
  NODEJS_VERSION: "stable"

install:
- ps: >-
    Install-Product node $env:NODEJS_VERSION

    choco install GoogleChrome

    choco install Firefox

- cmd: >-
    node --version

    npm --version

    npm install

    node node_modules/gulp/bin/gulp build

    mkdir ..\testcafe

    cd ..\testcafe

    git clone https://github.com/DevExpress/testcafe .

    npm install testcafe-hammerhead ../testcafe-hammerhead --save

    npm install

build: off

# NOTE: We should prerun Firefox to avoid "Refresh Firefox" notification in the tests window.
test_script:
- cmd: >-
    start /D "C:\Program Files (x86)\Mozilla Firefox" firefox.exe -new-window https://google.com

    npm test