export const INJECTOR_RESOURCE_DECODING_FAILED = 'INJECTOR_RESOURCE_DECODING_FAILED';
export const INJECTOR_RESOURCE_ENCODING_FAILED = 'INJECTOR_RESOURCE_ENCODING_FAILED';

export const PROXY_ORIGIN_SERVER_CONNECTION_TERMINATED = 'PROXY_ORIGIN_SERVER_CONNECTION_TERMINATED';
export const PROXY_CANT_RESOLVE_ORIGIN_URL = 'PROXY_CANT_RESOLVE_ORIGIN_URL';
export const PROXY_ORIGIN_SERVER_REQUEST_TIMEOUT = 'PROXY_ORIGIN_SERVER_REQUEST_TIMEOUT';
