name: On-release

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    if: ${{ !github.event.release.draft }}
    runs-on: ubuntu-latest
    environment: npmjs
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event.release.target_commitish }}

      - uses: DevExpress/testcafe-build-system/actions/publish@main
        with:
          pre-publish-script: gulp test-server
          audit-level: critical
          omit-dev-dependencies: true
          branch: ${{ github.event.release.target_commitish }}
          version: ${{ github.event.release.tag_name }}