name: Test Server (Minimum)

on:
  workflow_dispatch:
    inputs:
      sha:
        desciption: 'The test commit SHA or ref'
        required: true
        default: 'master'
      merged_sha:
        description: 'The merge commit SHA' 
      deploy_run_id:
        description: 'The ID of a deployment workspace run with artifacts'
jobs:  
  test:
    runs-on: ubuntu-latest
    environment: test-server
    steps:
      - uses: DevExpress/testcafe-build-system/actions/set-status@main
        with:
          status: 'pending'
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.inputs.merged_sha || github.event.inputs.sha}}
          
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: DevExpress/testcafe-build-system/actions/read-artifacts@main
        with:
          package-name: 'testcafe-hammerhead'
          
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npx gulp test-server --no-build
        timeout-minutes: 60

      - uses: DevExpress/testcafe-build-system/actions/set-status@main
        if: always()
        with:
          status: ${{ fromJSON('["failure", "success"]')[job.status == 'success'] }}
