name: Test Client (Cloud)

on:
  workflow_dispatch:
    inputs:
      sha:
        desciption: 'The test commit SHA or ref'
        required: true
        default: 'master'
      merged_sha:
        description: 'The merge commit SHA'
      deploy_run_id:
        description: 'The ID of a deployment workspace run with artifacts'
jobs:
  test:
    runs-on: ubuntu-latest
    environment: test-client
    env:
      SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      # NOTE: Test server on Android Emulator 7.1 and later can be accessed only via hostname.
      # We are forced to add this variable to say the 'qunit-harness' module uses the hostname for the test server URL.
      # https://github.com/AlexanderMoskovkin/qunit-harness/blob/master/src/index.js#L119
      TRAVIS: true
    steps:
      - uses: DevExpress/testcafe-build-system/actions/set-status@main
        with:
          status: 'pending'
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.inputs.merged_sha || github.event.inputs.sha}}

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - uses: DevExpress/testcafe-build-system/actions/read-artifacts@main
        with:
          package-name: 'testcafe-hammerhead'

      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npx gulp test-client-cloud --no-build
        timeout-minutes: 60

      - uses: DevExpress/testcafe-build-system/actions/set-status@main
        if: always()
        with:
          status: ${{ fromJSON('["failure", "success"]')[job.status == 'success'] }}
